theme: jekyll-theme-tactile
title: Bienvenidos al laboratorio de ingeniería del conocimiento
description: Espacio colaborativo de vincunlación con el Laboratorio de Simulación e Investigación Tecnológica del Instituto Politécnico Nacional
